// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Map: typeof import('./components/templates/map/index.vue')['default']
    SideBarDetails: typeof import('./components/organisms/sideBarDetails/index.vue')['default']
    SidebarRight: typeof import('./components/templates/sidebar-right/index.vue')['default']
    SideBarTools: typeof import('./components/organisms/sideBarTools/index.vue')['default']
  }
}

export { }
